//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_banking_screen_H
#define METASPRITE_banking_screen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define banking_screen_TILE_ORIGIN 0
#define banking_screen_TILE_W 8
#define banking_screen_TILE_H 8
#define banking_screen_WIDTH 160
#define banking_screen_HEIGHT 144
#define banking_screen_TILE_COUNT 53
#define banking_screen_PALETTE_COUNT 1
#define banking_screen_COLORS_PER_PALETTE 4
#define banking_screen_TOTAL_COLORS 4
#define banking_screen_MAP_ATTRIBUTES 0

BANKREF_EXTERN(banking)

extern const palette_color_t banking_screen_palettes[4];
extern const uint8_t banking_screen_tiles[848];

extern const unsigned char banking_screen_map[360];
#define banking_screen_map_attributes banking_screen_map

#endif
