//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gbdk_splash_screen_H
#define METASPRITE_gbdk_splash_screen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gbdk_splash_screen_TILE_ORIGIN 0
#define gbdk_splash_screen_TILE_W 8
#define gbdk_splash_screen_TILE_H 8
#define gbdk_splash_screen_WIDTH 160
#define gbdk_splash_screen_HEIGHT 144
#define gbdk_splash_screen_TILE_COUNT 57
#define gbdk_splash_screen_PALETTE_COUNT 1
#define gbdk_splash_screen_COLORS_PER_PALETTE 4
#define gbdk_splash_screen_TOTAL_COLORS 4
#define gbdk_splash_screen_MAP_ATTRIBUTES 0

BANKREF_EXTERN(gbdk_splash_screen)

extern const palette_color_t gbdk_splash_screen_palettes[4];
extern const uint8_t gbdk_splash_screen_tiles[912];

extern const unsigned char gbdk_splash_screen_map[360];
#define gbdk_splash_screen_map_attributes gbdk_splash_screen_map

#endif
