//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_banking_H
#define METASPRITE_banking_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define banking_TILE_ORIGIN 0
#define banking_TILE_W 8
#define banking_TILE_H 8
#define banking_WIDTH 160
#define banking_HEIGHT 144
#define banking_TILE_COUNT 48
#define banking_PALETTE_COUNT 1
#define banking_COLORS_PER_PALETTE 4
#define banking_TOTAL_COLORS 4
#define banking_MAP_ATTRIBUTES 0

BANKREF_EXTERN(banking)

extern const palette_color_t banking_palettes[4];
extern const uint8_t banking_tiles[768];

extern const unsigned char banking_map[360];
#define banking_map_attributes banking_map

#endif
